import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

import { assertLocalSupabaseUrl, parseSupabaseEnv } from "./local-supabase.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "../..");
const ENV_PATH = join(ROOT, ".env.local");
const PASSWORD = "LocalSmartMap123!";
const FIXTURES = [
  ["admin@smartmap.example", "Local Administrator"],
  ["owner@smartmap.example", "Local Boarding-House Owner"],
  ["reviewer@smartmap.example", "Local Reviewer"],
  ["student@smartmap.example", "Local Student"],
];

function statusEnvironment() {
  const output = execFileSync("npx", ["--yes", "supabase@2.107.0", "status", "-o", "env"], {
    cwd: ROOT,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  const env = parseSupabaseEnv(output);
  const url = assertLocalSupabaseUrl(env.API_URL);
  const anonKey = env.ANON_KEY || env.PUBLISHABLE_KEY;
  const serviceKey = env.SERVICE_ROLE_KEY || env.SECRET_KEY;
  if (!anonKey || !serviceKey) {
    throw new Error("Supabase status did not return local API keys.");
  }
  return { url, anonKey, serviceKey };
}

function parseDotEnv(raw) {
  const values = {};
  for (const line of raw.split(/\r?\n/)) {
    const match = line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/);
    if (match) values[match[1]] = match[2].replace(/^(["'])(.*)\1$/, "$2");
  }
  return values;
}

function ensureLocalEnv({ url, anonKey, serviceKey }) {
  if (existsSync(ENV_PATH)) {
    const current = parseDotEnv(readFileSync(ENV_PATH, "utf8"));
    if (current.NEXT_PUBLIC_SUPABASE_URL) {
      try {
        assertLocalSupabaseUrl(current.NEXT_PUBLIC_SUPABASE_URL);
        return;
      } catch {
        throw new Error(
          ".env.local already targets a non-local project; it was left untouched. Move it aside before local bootstrap.",
        );
      }
    }
    throw new Error(".env.local already exists without a local Supabase URL; it was left untouched.");
  }

  const pepper = randomBytes(32).toString("hex");
  const contents = [
    "# Generated by npm run dev:bootstrap for loopback-only development.",
    `NEXT_PUBLIC_SUPABASE_URL=${url}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}`,
    `SUPABASE_SERVICE_ROLE_KEY=${serviceKey}`,
    "NEXT_PUBLIC_TURNSTILE_SITE_KEY=1x00000000000000000000AA",
    "TURNSTILE_SECRET_KEY=1x0000000000000000000000000000000AA",
    `ABUSE_RATE_LIMIT_PEPPER=${pepper}`,
    "EMAIL_PROVIDER=disabled",
    "",
  ].join("\n");
  writeFileSync(ENV_PATH, contents, { encoding: "utf8", mode: 0o600, flag: "wx" });
}

async function findUser(client, email) {
  for (let page = 1; page <= 5; page += 1) {
    const { data, error } = await client.auth.admin.listUsers({ page, perPage: 200 });
    if (error) throw error;
    const user = data.users.find((candidate) => candidate.email === email);
    if (user) return user;
    if (data.users.length < 200) return null;
  }
  return null;
}

async function ensureUser(client, email, fullName) {
  let user = await findUser(client, email);
  if (!user) {
    const { data, error } = await client.auth.admin.createUser({
      email,
      password: PASSWORD,
      email_confirm: true,
      user_metadata: { full_name: fullName },
    });
    if (error) throw error;
    user = data.user;
  } else {
    const { error } = await client.auth.admin.updateUserById(user.id, {
      password: PASSWORD,
      email_confirm: true,
      user_metadata: { full_name: fullName },
    });
    if (error) throw error;
  }
  return user;
}

async function main() {
  const local = statusEnvironment();
  if (!process.argv.includes("--skip-env-file")) {
    ensureLocalEnv(local);
  }
  const client = createClient(local.url, local.serviceKey, { auth: { persistSession: false } });
  const users = new Map();
  for (const [email, fullName] of FIXTURES) {
    users.set(email, await ensureUser(client, email, fullName));
  }

  const roles = [
    { user_id: users.get("admin@smartmap.example").id, role: "admin" },
    { user_id: users.get("owner@smartmap.example").id, role: "boarding_house_owner" },
  ];
  const { error: roleError } = await client.from("app_user_roles").upsert(roles, {
    onConflict: "user_id,role",
  });
  if (roleError) throw roleError;

  execFileSync(process.execPath, [join(ROOT, "tools/qa/seed-boarding-houses.mjs")], {
    cwd: ROOT,
    stdio: "inherit",
    env: {
      ...process.env,
      NEXT_PUBLIC_SUPABASE_URL: local.url,
      NEXT_PUBLIC_SUPABASE_ANON_KEY: local.anonKey,
      SUPABASE_SERVICE_ROLE_KEY: local.serviceKey,
    },
  });

  console.log("Local SmartMap bootstrap complete.");
  console.log("Fixture password: LocalSmartMap123! (loopback development only)");
}

main().catch((error) => {
  console.error(`Local bootstrap failed: ${error.message}`);
  process.exit(1);
});
