-- Audited room-data reset.
-- Generated by tools/room-data/generate_room_migration.py.
-- Remarks/status columns from the 2023-2024 utilization pages are intentionally not imported.

BEGIN;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'FT')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DFST') THEN
    UPDATE facilities SET code = 'DFST' WHERE code = 'FT';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'ABE')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DABE') THEN
    UPDATE facilities SET code = 'DABE' WHERE code = 'ABE';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'GE')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DGE') THEN
    UPDATE facilities SET code = 'DGE' WHERE code = 'GE';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'ME')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DME') THEN
    UPDATE facilities SET code = 'DME' WHERE code = 'ME';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'MECH')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DME') THEN
    UPDATE facilities SET code = 'DME' WHERE code = 'MECH';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'ECON')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DOE') THEN
    UPDATE facilities SET code = 'DOE' WHERE code = 'ECON';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'DECON')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DOE') THEN
    UPDATE facilities SET code = 'DOE' WHERE code = 'DECON';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'BIOTECH')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DBT') THEN
    UPDATE facilities SET code = 'DBT' WHERE code = 'BIOTECH';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'DTED')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DTE') THEN
    UPDATE facilities SET code = 'DTE' WHERE code = 'DTED';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'DTM')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DTHM') THEN
    UPDATE facilities SET code = 'DTHM' WHERE code = 'DTM';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'CVM')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DVM') THEN
    UPDATE facilities SET code = 'DVM' WHERE code = 'CVM';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'CSAT')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DCST') THEN
    UPDATE facilities SET code = 'DCST' WHERE code = 'CSAT';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'MATH')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DMATH') THEN
    UPDATE facilities SET code = 'DMATH' WHERE code = 'MATH';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'PHYS')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DPHYS') THEN
    UPDATE facilities SET code = 'DPHYS' WHERE code = 'PHYS';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'STAT')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DSTAT') THEN
    UPDATE facilities SET code = 'DSTAT' WHERE code = 'STAT';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM facilities WHERE code = 'CHEM')
     AND NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DOPAC') THEN
    UPDATE facilities SET code = 'DOPAC' WHERE code = 'CHEM';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DA')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-agronomy') THEN
    UPDATE facilities
    SET code = 'DA'
    WHERE slug = 'department-of-agronomy';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DABE')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-agricultural-and-biosystems-engineering') THEN
    UPDATE facilities
    SET code = 'DABE'
    WHERE slug = 'department-of-agricultural-and-biosystems-engineering';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DAEEX')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-agricultural-education-and-extension') THEN
    UPDATE facilities
    SET code = 'DAEEX'
    WHERE slug = 'department-of-agricultural-education-and-extension';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DALL')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-arts-languages-and-literature') THEN
    UPDATE facilities
    SET code = 'DALL'
    WHERE slug = 'department-of-arts-languages-and-literature';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DAS')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-animal-science') THEN
    UPDATE facilities
    SET code = 'DAS'
    WHERE slug = 'department-of-animal-science';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DBM')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-business-and-management') THEN
    UPDATE facilities
    SET code = 'DBM'
    WHERE slug = 'department-of-business-and-management';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DBS')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-biological-sciences') THEN
    UPDATE facilities
    SET code = 'DBS'
    WHERE slug = 'department-of-biological-sciences';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DBT')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-biotechnology') THEN
    UPDATE facilities
    SET code = 'DBT'
    WHERE slug = 'department-of-biotechnology';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DCE')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-civil-engineering') THEN
    UPDATE facilities
    SET code = 'DCE'
    WHERE slug = 'department-of-civil-engineering';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DCST')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-computer-science-and-technology') THEN
    UPDATE facilities
    SET code = 'DCST'
    WHERE slug = 'department-of-computer-science-and-technology';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DDC')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-development-communication') THEN
    UPDATE facilities
    SET code = 'DDC'
    WHERE slug = 'department-of-development-communication';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DFS')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-forest-science') THEN
    UPDATE facilities
    SET code = 'DFS'
    WHERE slug = 'department-of-forest-science';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DFST')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-food-science-and-technology') THEN
    UPDATE facilities
    SET code = 'DFST'
    WHERE slug = 'department-of-food-science-and-technology';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DGE')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-geodetic-engineering') THEN
    UPDATE facilities
    SET code = 'DGE'
    WHERE slug = 'department-of-geodetic-engineering';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DLABS')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'former-dlabs-building') THEN
    UPDATE facilities
    SET code = 'DLABS'
    WHERE slug = 'former-dlabs-building';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DMATH')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-mathematics') THEN
    UPDATE facilities
    SET code = 'DMATH'
    WHERE slug = 'department-of-mathematics';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DME')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-mechanical-engineering') THEN
    UPDATE facilities
    SET code = 'DME'
    WHERE slug = 'department-of-mechanical-engineering';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DMET')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-meteorology') THEN
    UPDATE facilities
    SET code = 'DMET'
    WHERE slug = 'department-of-meteorology';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DOE')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-economics') THEN
    UPDATE facilities
    SET code = 'DOE'
    WHERE slug = 'department-of-economics';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DOH')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-horticulture') THEN
    UPDATE facilities
    SET code = 'DOH'
    WHERE slug = 'department-of-horticulture';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DON')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'faculty-of-nursing') THEN
    UPDATE facilities
    SET code = 'DON'
    WHERE slug = 'faculty-of-nursing';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DOPAC')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-pure-and-applied-chemistry') THEN
    UPDATE facilities
    SET code = 'DOPAC'
    WHERE slug = 'department-of-pure-and-applied-chemistry';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DPBG')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-plant-breeding-and-genetics') THEN
    UPDATE facilities
    SET code = 'DPBG'
    WHERE slug = 'department-of-plant-breeding-and-genetics';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DPHYS')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-physics') THEN
    UPDATE facilities
    SET code = 'DPHYS'
    WHERE slug = 'department-of-physics';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DPM')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-pest-management') THEN
    UPDATE facilities
    SET code = 'DPM'
    WHERE slug = 'department-of-pest-management';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DPSS')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-philosophy-and-social-sciences') THEN
    UPDATE facilities
    SET code = 'DPSS'
    WHERE slug = 'department-of-philosophy-and-social-sciences';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DSS')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-soil-science') THEN
    UPDATE facilities
    SET code = 'DSS'
    WHERE slug = 'department-of-soil-science';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DSTAT')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-statistics') THEN
    UPDATE facilities
    SET code = 'DSTAT'
    WHERE slug = 'department-of-statistics';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DTE')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-teacher-education') THEN
    UPDATE facilities
    SET code = 'DTE'
    WHERE slug = 'department-of-teacher-education';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DTHM')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'department-of-tourism-and-hospitality-management') THEN
    UPDATE facilities
    SET code = 'DTHM'
    WHERE slug = 'department-of-tourism-and-hospitality-management';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'DVM')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'faculty-of-veterinary-medicine') THEN
    UPDATE facilities
    SET code = 'DVM'
    WHERE slug = 'faculty-of-veterinary-medicine';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'IHK')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'institute-of-human-kinetics') THEN
    UPDATE facilities
    SET code = 'IHK'
    WHERE slug = 'institute-of-human-kinetics';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'ISRDS')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'institute-for-strategic-research-and-development-studies') THEN
    UPDATE facilities
    SET code = 'ISRDS'
    WHERE slug = 'institute-for-strategic-research-and-development-studies';
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM facilities WHERE code = 'ITEEM')
     AND EXISTS (SELECT 1 FROM facilities WHERE slug = 'institute-of-tropical-ecology-and-environmental-management') THEN
    UPDATE facilities
    SET code = 'ITEEM'
    WHERE slug = 'institute-of-tropical-ecology-and-environmental-management';
  END IF;
END $$;

-- Remove rooms from earlier generated imports before inserting the audited 189-room set.
DELETE FROM rooms
WHERE facility_id IN (
  SELECT id FROM facilities
  WHERE code = ANY (ARRAY[
    'ABE', 'ADMIN', 'BIOTECH', 'CAF', 'CAS', 'CET', 'CFNR', 'CHEM', 'COMART', 'CSAT', 'CVM', 'DA', 'DABE', 'DAEEX', 'DALL', 'DAS', 'DBM', 'DBS', 'DBT', 'DCE', 'DCST', 'DDC', 'DECON', 'DFS', 'DFST', 'DGE', 'DHM', 'DLABS', 'DMATH', 'DME', 'DMET', 'DOE', 'DOH', 'DON', 'DOPAC', 'DPBG', 'DPHYS', 'DPM', 'DPSS', 'DSS', 'DSTAT', 'DTE', 'DTED', 'DTHM', 'DTM', 'DVM', 'ECON', 'FON', 'FT', 'GE', 'HIGHSC', 'HOMESCI', 'IHK', 'ISRDS', 'ITEEM', 'MATH', 'MATHNS', 'ME', 'MECH', 'NURS', 'PHYS', 'STAT', 'VACADMIN'
  ]::text[])
);

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Agronomy',
  'department-of-agronomy',
  'Faculty of Agriculture and Food Science (FAFS); formerly under College of Agriculture and Food Science (CAFS). Search aliases: DA, Dept. of Agronomy.',
  'academic',
  true,
  10.7461,
  124.7933,
  'DA'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Agricultural and Biosystems Engineering',
  'department-of-agricultural-and-biosystems-engineering',
  'Faculty of Engineering (FE); formerly under College of Engineering and Technology (CET). Search aliases: ABE, DABE.',
  'academic',
  true,
  10.7455,
  124.7935,
  'DABE'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Agricultural Education and Extension',
  'department-of-agricultural-education-and-extension',
  'Faculty of Agriculture and Food Science (FAFS); formerly under College of Agriculture and Food Science (CAFS). Search aliases: DAEEX, DAEEx.',
  'academic',
  true,
  10.7461,
  124.7933,
  'DAEEX'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Arts, Languages, and Literature',
  'department-of-arts-languages-and-literature',
  'Faculty of Humanities and Social Sciences (FHSS); formerly under College of Arts and Sciences (CAS). Search aliases: DALL, Department of Arts, Languages and Literature.',
  'academic',
  true,
  10.7431,
  124.7942,
  'DALL'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Animal Science',
  'department-of-animal-science',
  'Faculty of Agriculture and Food Science (FAFS); formerly under College of Agriculture and Food Science (CAFS). Search aliases: DAS.',
  'academic',
  true,
  10.7475,
  124.7932,
  'DAS'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Business and Management',
  'department-of-business-and-management',
  'Faculty of Management and Economics (FME); formerly under College of Management and Economics (CME). Search aliases: DBM, Department of Business Management.',
  'academic',
  true,
  10.7445,
  124.7952,
  'DBM'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Biological Sciences',
  'department-of-biological-sciences',
  'Faculty of Natural and Mathematical Sciences (FNMS); formerly under College of Arts and Sciences (CAS). Search aliases: DBS.',
  'academic',
  true,
  10.7431,
  124.7942,
  'DBS'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Biotechnology',
  'department-of-biotechnology',
  'Faculty of Natural and Mathematical Sciences (FNMS); formerly under College of Arts and Sciences (CAS). Search aliases: BIOTECH, DBT, DBt.',
  'academic',
  true,
  10.7431,
  124.7942,
  'DBT'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Civil Engineering',
  'department-of-civil-engineering',
  'Faculty of Engineering (FE); formerly under College of Engineering and Technology (CET). Search aliases: DCE.',
  'academic',
  true,
  10.7455,
  124.7935,
  'DCE'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Computer Science and Technology',
  'department-of-computer-science-and-technology',
  'Faculty of Computing (FOC); formerly under College of Engineering and Technology (CET). Search aliases: CSAT, DCST.',
  'academic',
  true,
  10.7455,
  124.7935,
  'DCST'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Development Communication',
  'department-of-development-communication',
  'Faculty of Agriculture and Food Science (FAFS); formerly under College of Agriculture and Food Science (CAFS). Search aliases: DDC, DevCom.',
  'academic',
  true,
  10.7447,
  124.7949,
  'DDC'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Forest Science',
  'department-of-forest-science',
  'Faculty of Forestry and Environmental Science (FFES); formerly under College of Forestry and Environmental Science (CFES). Search aliases: CFES, CFNR, DFS.',
  'academic',
  true,
  10.7485,
  124.7925,
  'DFS'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Food Science and Technology',
  'department-of-food-science-and-technology',
  'Faculty of Agriculture and Food Science (FAFS); formerly under College of Agriculture and Food Science (CAFS). Search aliases: DFST, FT, FoodTech.',
  'academic',
  true,
  10.7476,
  124.7928,
  'DFST'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Geodetic Engineering',
  'department-of-geodetic-engineering',
  'Faculty of Engineering (FE); formerly under College of Engineering and Technology (CET). Search aliases: DGE, GE.',
  'academic',
  true,
  10.7455,
  124.7935,
  'DGE'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Former DLABS Building',
  'former-dlabs-building',
  'Faculty of Humanities and Social Sciences (FHSS); formerly under College of Arts and Sciences (CAS). Search aliases: DLABS, Department of Arts, Languages, and Literature, Department of Liberal Arts and Behavioral Sciences, Department of Philosophy and Social Sciences.',
  'academic',
  true,
  10.7431,
  124.7942,
  'DLABS'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Mathematics',
  'department-of-mathematics',
  'Faculty of Natural and Mathematical Sciences (FNMS); formerly under College of Arts and Sciences (CAS). Search aliases: DMATH, DMath.',
  'academic',
  true,
  10.7431,
  124.7942,
  'DMATH'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Mechanical Engineering',
  'department-of-mechanical-engineering',
  'Faculty of Engineering (FE); formerly under College of Engineering and Technology (CET). Search aliases: DME, ME, MECH.',
  'academic',
  true,
  10.7455,
  124.7935,
  'DME'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Meteorology',
  'department-of-meteorology',
  'Faculty of Engineering (FE); formerly under College of Engineering and Technology (CET). Search aliases: DMET, DMet.',
  'academic',
  true,
  10.7455,
  124.7935,
  'DMET'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Economics',
  'department-of-economics',
  'Faculty of Management and Economics (FME); formerly under College of Management and Economics (CME). Search aliases: DOE, DoE, ECON.',
  'academic',
  true,
  10.7445,
  124.7952,
  'DOE'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Horticulture',
  'department-of-horticulture',
  'Faculty of Agriculture and Food Science (FAFS); formerly under College of Agriculture and Food Science (CAFS). Search aliases: DOH.',
  'academic',
  true,
  10.7461,
  124.7933,
  'DOH'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Faculty of Nursing',
  'faculty-of-nursing',
  'Faculty of Nursing (FON); formerly under College of Nursing (CON). Search aliases: CON, DON, Department of Nursing, FON.',
  'academic',
  true,
  10.744,
  124.7955,
  'DON'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Pure and Applied Chemistry',
  'department-of-pure-and-applied-chemistry',
  'Faculty of Natural and Mathematical Sciences (FNMS); formerly under College of Arts and Sciences (CAS). Search aliases: CHEM, DOPAC, DoPAC.',
  'academic',
  true,
  10.7431,
  124.7942,
  'DOPAC'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Plant Breeding and Genetics',
  'department-of-plant-breeding-and-genetics',
  'Faculty of Agriculture and Food Science (FAFS); formerly under College of Agriculture and Food Science (CAFS). Search aliases: DPBG.',
  'academic',
  true,
  10.7461,
  124.7933,
  'DPBG'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Physics',
  'department-of-physics',
  'Faculty of Natural and Mathematical Sciences (FNMS); formerly under College of Arts and Sciences (CAS). Search aliases: DPHYS, DPhys, PHYS.',
  'academic',
  true,
  10.7431,
  124.7942,
  'DPHYS'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Pest Management',
  'department-of-pest-management',
  'Faculty of Agriculture and Food Science (FAFS); formerly under College of Agriculture and Food Science (CAFS). Search aliases: DPM.',
  'academic',
  true,
  10.7461,
  124.7933,
  'DPM'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Philosophy and Social Sciences',
  'department-of-philosophy-and-social-sciences',
  'Faculty of Humanities and Social Sciences (FHSS); formerly under College of Arts and Sciences (CAS). Search aliases: DPSS.',
  'academic',
  true,
  10.7431,
  124.7942,
  'DPSS'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Soil Science',
  'department-of-soil-science',
  'Faculty of Agriculture and Food Science (FAFS); formerly under College of Agriculture and Food Science (CAFS). Search aliases: DSS.',
  'academic',
  true,
  10.7461,
  124.7933,
  'DSS'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Statistics',
  'department-of-statistics',
  'Faculty of Natural and Mathematical Sciences (FNMS); formerly under College of Arts and Sciences (CAS). Search aliases: DSTAT, DStat, DepStat, STAT.',
  'academic',
  true,
  10.7431,
  124.7942,
  'DSTAT'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Teacher Education',
  'department-of-teacher-education',
  'Faculty of Teacher Education (FTE); formerly under College of Education (CTE). Search aliases: DTE, DTED, Department of Teacher Education.',
  'academic',
  true,
  10.7435,
  124.796,
  'DTE'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Department of Tourism and Hospitality Management',
  'department-of-tourism-and-hospitality-management',
  'Faculty of Management and Economics (FME); formerly under College of Management and Economics (CME). Search aliases: DCHM, DHM, DTHM, DTM, Department of Consumer and Hospitality Management, Department of Hospitality Management, Department of Tourism Management.',
  'academic',
  true,
  10.7451,
  124.795,
  'DTHM'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Faculty of Veterinary Medicine',
  'faculty-of-veterinary-medicine',
  'Faculty of Veterinary Medicine (FVM); formerly under College of Veterinary Medicine (CVM). Search aliases: CVM, DVM, Department of Veterinary Medicine, FVM.',
  'academic',
  true,
  10.75,
  124.79,
  'DVM'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Institute of Human Kinetics',
  'institute-of-human-kinetics',
  'Faculty of Teacher Education (FTE); formerly under College of Education (CTE). Search aliases: IHK.',
  'academic',
  true,
  10.742,
  124.797,
  'IHK'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Institute for Strategic Research and Development Studies',
  'institute-for-strategic-research-and-development-studies',
  'Faculty of Humanities and Social Sciences (FHSS); formerly under College of Management and Economics (CME). Search aliases: ISRDS, Institute of Strategic Research and Development Studies.',
  'academic',
  true,
  10.7445,
  124.7952,
  'ISRDS'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

INSERT INTO facilities (name, slug, description, category, has_rooms, latitude, longitude, code)
VALUES (
  'Institute of Tropical Ecology and Environmental Management',
  'institute-of-tropical-ecology-and-environmental-management',
  'Faculty of Forestry and Environmental Science (FFES); formerly under College of Forestry and Environmental Science (CFES). Search aliases: ITEEM.',
  'academic',
  true,
  10.7485,
  124.7925,
  'ITEEM'
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  has_rooms = true;

-- Canonical rooms from the wide table: 189 nonblank room cells.
INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DA - CONFERENCE ROOM',
  NULL,
  NULL,
  'Capacity: 10'
FROM facilities
WHERE code = 'DA'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DA PSB Rm-1',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'DA'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DA PSB Rm-2',
  NULL,
  NULL,
  'Capacity: 50'
FROM facilities
WHERE code = 'DA'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DA Rm-201',
  NULL,
  2,
  'Capacity: 30'
FROM facilities
WHERE code = 'DA'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DA Rm-202',
  NULL,
  2,
  'Capacity: 30'
FROM facilities
WHERE code = 'DA'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DA Rm-203 / SMART ROOM',
  NULL,
  2,
  'Capacity: 50'
FROM facilities
WHERE code = 'DA'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'PSB Rm-10',
  NULL,
  NULL,
  'Capacity: 60'
FROM facilities
WHERE code = 'DAEEX'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'PSB Rm-9',
  NULL,
  NULL,
  'Capacity: 60'
FROM facilities
WHERE code = 'DAEEX'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DAS CONFERENCE ROOM',
  NULL,
  NULL,
  'Capacity: 12'
FROM facilities
WHERE code = 'DAS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DAS MEAT LABORATORY',
  NULL,
  NULL,
  'Capacity: 35'
FROM facilities
WHERE code = 'DAS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DAS-1',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DAS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DAS-2',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DAS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DAS-3',
  NULL,
  NULL,
  'Capacity: 60'
FROM facilities
WHERE code = 'DAS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DAS-5',
  NULL,
  NULL,
  'Capacity: 35'
FROM facilities
WHERE code = 'DAS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DAS-7',
  NULL,
  NULL,
  'Capacity: 35'
FROM facilities
WHERE code = 'DAS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ADE-123A',
  NULL,
  1,
  'Capacity: 20'
FROM facilities
WHERE code = 'DDC'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ADE-218',
  NULL,
  2,
  'Capacity: 45'
FROM facilities
WHERE code = 'DDC'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DDC-NEW ROOM',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DDC'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFST FM Rm',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'DFST'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFST LECTURE ROOM',
  NULL,
  NULL,
  'Capacity: 50'
FROM facilities
WHERE code = 'DFST'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFST LIBRARY',
  NULL,
  NULL,
  'Capacity: 10'
FROM facilities
WHERE code = 'DFST'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFST PILOT ROOM',
  NULL,
  NULL,
  'Capacity: 60'
FROM facilities
WHERE code = 'DFST'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFST SENSORY ROOM',
  NULL,
  NULL,
  'Capacity: 25'
FROM facilities
WHERE code = 'DFST'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DOH-101',
  NULL,
  1,
  'Capacity: 80'
FROM facilities
WHERE code = 'DOH'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DOH-202',
  NULL,
  2,
  'Capacity: 35'
FROM facilities
WHERE code = 'DOH'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DOH-CropPhy (Hort)',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'DOH'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DOH-Ornam',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'DOH'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DOH-Post har (Hort)',
  NULL,
  NULL,
  'Capacity: 35'
FROM facilities
WHERE code = 'DOH'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'PSB DOH-05',
  NULL,
  NULL,
  'Capacity: 50'
FROM facilities
WHERE code = 'DOH'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPBG LR-1',
  NULL,
  NULL,
  'Capacity: 60'
FROM facilities
WHERE code = 'DPBG'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPBG-204',
  NULL,
  2,
  'Capacity: 40'
FROM facilities
WHERE code = 'DPBG'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPBG-LH',
  NULL,
  NULL,
  'Capacity: 60'
FROM facilities
WHERE code = 'DPBG'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPBG-PSB 11',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DPBG'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPBG-PSB 12',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DPBG'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPM PSB Rm-6',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DPM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPM-101',
  NULL,
  1,
  'Capacity: 100'
FROM facilities
WHERE code = 'DPM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPM-102',
  NULL,
  1,
  'Capacity: 40'
FROM facilities
WHERE code = 'DPM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPM-103',
  NULL,
  1,
  'Capacity: 35'
FROM facilities
WHERE code = 'DPM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPM-105',
  NULL,
  1,
  'Capacity: 35'
FROM facilities
WHERE code = 'DPM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPM-106',
  NULL,
  1,
  'Capacity: 35'
FROM facilities
WHERE code = 'DPM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPM-107',
  NULL,
  1,
  'Capacity: 35'
FROM facilities
WHERE code = 'DPM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DSS-116',
  NULL,
  1,
  'Capacity: 25'
FROM facilities
WHERE code = 'DSS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DSS-119',
  NULL,
  1,
  'Capacity: 100'
FROM facilities
WHERE code = 'DSS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DSS-205',
  NULL,
  2,
  'Capacity: 25'
FROM facilities
WHERE code = 'DSS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DSS-206',
  NULL,
  2,
  'Capacity: 25'
FROM facilities
WHERE code = 'DSS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'PSB-07',
  NULL,
  NULL,
  'Capacity: 50'
FROM facilities
WHERE code = 'DSS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'PSB-08',
  NULL,
  NULL,
  'Capacity: 50'
FROM facilities
WHERE code = 'DSS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DALL-2A1',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DALL'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DALL-2A2',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DALL'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DALL-3B',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DALL'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DALL-4B',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DALL'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DALL-6C',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DALL'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DALL-7C',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DALL'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DALL-ERR1',
  NULL,
  NULL,
  'Capacity: 60'
FROM facilities
WHERE code = 'DALL'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DBS-101',
  NULL,
  1,
  'Capacity: 60'
FROM facilities
WHERE code = 'DBS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DBS-102',
  NULL,
  1,
  'Capacity: 30'
FROM facilities
WHERE code = 'DBS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DBS-103',
  NULL,
  1,
  'Capacity: 30'
FROM facilities
WHERE code = 'DBS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DBS-104',
  NULL,
  1,
  'Capacity: 30'
FROM facilities
WHERE code = 'DBS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DBS-105',
  NULL,
  1,
  'Capacity: 30'
FROM facilities
WHERE code = 'DBS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DBS-106',
  NULL,
  1,
  'Capacity: 30'
FROM facilities
WHERE code = 'DBS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DBS-AnaLab',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'DBS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DBT-Lab1',
  NULL,
  NULL,
  'Capacity: 15'
FROM facilities
WHERE code = 'DBT'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DBT-Lab2',
  NULL,
  NULL,
  'Capacity: 25'
FROM facilities
WHERE code = 'DBT'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DBT-LecR1',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DBT'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DBT-LecR2',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DBT'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DLABS- AUDUTORIUM',
  NULL,
  NULL,
  'Capacity: 80'
FROM facilities
WHERE code = 'DLABS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DMATH CONF ROOM',
  NULL,
  NULL,
  'Capacity: 20'
FROM facilities
WHERE code = 'DMATH'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DMATH Lab',
  NULL,
  NULL,
  'Capacity: 20'
FROM facilities
WHERE code = 'DMATH'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DMath-LecR1',
  NULL,
  NULL,
  'Capacity: 60'
FROM facilities
WHERE code = 'DMATH'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DMath-LecR2',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DMATH'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DMath-LecR3',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DMATH'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DMath-LecR4',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DMATH'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DMath-LecR5',
  NULL,
  NULL,
  'Capacity: 35'
FROM facilities
WHERE code = 'DMATH'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'AC-105',
  NULL,
  1,
  'Capacity: 15'
FROM facilities
WHERE code = 'DOPAC'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'AC-106',
  NULL,
  1,
  'Capacity: 20'
FROM facilities
WHERE code = 'DOPAC'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'AC-108',
  NULL,
  1,
  'Capacity: 20'
FROM facilities
WHERE code = 'DOPAC'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'AC-206',
  NULL,
  2,
  'Capacity: 20'
FROM facilities
WHERE code = 'DOPAC'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'AC-208',
  NULL,
  2,
  'Capacity: 20'
FROM facilities
WHERE code = 'DOPAC'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'AC-209A',
  NULL,
  2,
  'Capacity: 30'
FROM facilities
WHERE code = 'DOPAC'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'AC-209B',
  NULL,
  2,
  'Capacity: 30'
FROM facilities
WHERE code = 'DOPAC'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'AC-210',
  NULL,
  2,
  'Capacity: 35'
FROM facilities
WHERE code = 'DOPAC'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPhys Comp. Lab',
  NULL,
  NULL,
  'Capacity: 15'
FROM facilities
WHERE code = 'DPHYS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPhys Lab 1',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'DPHYS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPhys Lab 2',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'DPHYS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPhys Lab 3',
  NULL,
  NULL,
  'Capacity: 20'
FROM facilities
WHERE code = 'DPHYS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPhys Lec 1',
  NULL,
  NULL,
  'Capacity: 50'
FROM facilities
WHERE code = 'DPHYS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPhys Lec 2',
  NULL,
  NULL,
  'Capacity: 50'
FROM facilities
WHERE code = 'DPHYS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPSS-10D',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DPSS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPSS-11D',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DPSS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPSS-12D',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DPSS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPSS-13D',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DPSS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPSS-5B1',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DPSS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPSS-8C',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DPSS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DPSS-9C',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DPSS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DStat Lab 1',
  NULL,
  NULL,
  'Capacity: 15'
FROM facilities
WHERE code = 'DSTAT'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DStat Lab 2',
  NULL,
  NULL,
  'Capacity: 15'
FROM facilities
WHERE code = 'DSTAT'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DStat Lab 3',
  NULL,
  NULL,
  'Capacity: 25'
FROM facilities
WHERE code = 'DSTAT'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DStat Lec 1',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DSTAT'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DStat Lec 2',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DSTAT'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DStat LH',
  NULL,
  NULL,
  'Capacity: 75'
FROM facilities
WHERE code = 'DSTAT'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'CPB 01',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'DABE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'CPB 02',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DABE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-101',
  NULL,
  1,
  'Capacity: 30'
FROM facilities
WHERE code = 'DABE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-105',
  NULL,
  1,
  'Capacity: 60'
FROM facilities
WHERE code = 'DABE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-106',
  NULL,
  1,
  'Capacity: 60'
FROM facilities
WHERE code = 'DABE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-202',
  NULL,
  2,
  'Capacity: 60'
FROM facilities
WHERE code = 'DABE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'SLH',
  NULL,
  NULL,
  'Capacity: 80'
FROM facilities
WHERE code = 'DABE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DCE- MTLR',
  NULL,
  NULL,
  'Capacity: 20'
FROM facilities
WHERE code = 'DCE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-101Anx',
  NULL,
  1,
  'Capacity: 35'
FROM facilities
WHERE code = 'DCE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-102 Anx',
  NULL,
  1,
  'Capacity: 35'
FROM facilities
WHERE code = 'DCE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-103 Anx',
  NULL,
  1,
  'Capacity: 35'
FROM facilities
WHERE code = 'DCE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-103 comp. Lab',
  NULL,
  1,
  'Capacity: 25'
FROM facilities
WHERE code = 'DCE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-107 DRAFTING Rm',
  NULL,
  1,
  'Capacity: 30'
FROM facilities
WHERE code = 'DCE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'Soils Mech Lab.',
  NULL,
  NULL,
  'Capacity: 20'
FROM facilities
WHERE code = 'DCE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ICT-101',
  NULL,
  1,
  'Capacity: 40'
FROM facilities
WHERE code = 'DCST'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ICT-102 / OFFICE ROOM',
  NULL,
  1,
  'Capacity: 24'
FROM facilities
WHERE code = 'DCST'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ICT-103',
  NULL,
  1,
  'Capacity: 20'
FROM facilities
WHERE code = 'DCST'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ICT-201',
  NULL,
  2,
  'Capacity: 60'
FROM facilities
WHERE code = 'DCST'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ICT-202',
  NULL,
  2,
  'Capacity: 30'
FROM facilities
WHERE code = 'DCST'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ICT-203',
  NULL,
  2,
  'Capacity: 30'
FROM facilities
WHERE code = 'DCST'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-102',
  NULL,
  1,
  'Capacity: 25'
FROM facilities
WHERE code = 'DGE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-201 Anx',
  NULL,
  2,
  'Capacity: 40'
FROM facilities
WHERE code = 'DGE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-202 Anx',
  NULL,
  2,
  'Capacity: 40'
FROM facilities
WHERE code = 'DGE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-203 Anx',
  NULL,
  2,
  'Capacity: 40'
FROM facilities
WHERE code = 'DGE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-204',
  NULL,
  2,
  'Capacity: 40'
FROM facilities
WHERE code = 'DGE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DME-LR 1',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DME'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DME-LR 2',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DME'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DME-LR 4',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'DME'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-104 Anx',
  NULL,
  1,
  'Capacity: 40'
FROM facilities
WHERE code = 'DMET'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-105 Anx',
  NULL,
  1,
  'Capacity: 40'
FROM facilities
WHERE code = 'DMET'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'EB-201 Comp. Lab',
  NULL,
  2,
  'Capacity: 25'
FROM facilities
WHERE code = 'DMET'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFS COMPUTER ROOM',
  NULL,
  NULL,
  'Capacity: 50'
FROM facilities
WHERE code = 'DFS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFS TRAINING ROOM',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DFS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFS-A3',
  NULL,
  NULL,
  'Capacity: 60'
FROM facilities
WHERE code = 'DFS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFS-A5',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DFS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFS-AVR',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'DFS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFS-B12',
  NULL,
  NULL,
  'Capacity: 180'
FROM facilities
WHERE code = 'DFS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFS-C11',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'DFS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFS-C21',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DFS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFS-C22',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DFS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DFS-C23',
  NULL,
  NULL,
  'Capacity: 45'
FROM facilities
WHERE code = 'DFS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ITEEM-LR',
  NULL,
  NULL,
  'Capacity: 25'
FROM facilities
WHERE code = 'ITEEM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ADE-215',
  NULL,
  2,
  'Capacity: 50'
FROM facilities
WHERE code = 'DBM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ADE-216',
  NULL,
  2,
  'Capacity: 40'
FROM facilities
WHERE code = 'DBM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ECON-134',
  NULL,
  1,
  'Capacity: 40'
FROM facilities
WHERE code = 'DOE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ECON-135',
  NULL,
  1,
  'Capacity: 40'
FROM facilities
WHERE code = 'DOE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ECON-136',
  NULL,
  1,
  'Capacity: 40'
FROM facilities
WHERE code = 'DOE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ECON-234',
  NULL,
  2,
  'Capacity: 60'
FROM facilities
WHERE code = 'DOE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ECON-235',
  NULL,
  2,
  'Capacity: 60'
FROM facilities
WHERE code = 'DOE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DTHM-B1',
  NULL,
  NULL,
  'Capacity: 60'
FROM facilities
WHERE code = 'DTHM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DTHM-B2',
  NULL,
  NULL,
  'Capacity: 60'
FROM facilities
WHERE code = 'DTHM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DTHM-B3',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'DTHM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DTHM-B4',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'DTHM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DTHM-CTR',
  NULL,
  NULL,
  'Capacity: 60'
FROM facilities
WHERE code = 'DTHM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DTHM-DEMO ROOM',
  NULL,
  NULL,
  'Capacity: 50'
FROM facilities
WHERE code = 'DTHM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DTHM-FOOD LABORATORY',
  NULL,
  NULL,
  'Capacity: 25'
FROM facilities
WHERE code = 'DTHM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DTHM-FR',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DTHM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DTHM-MEETING ROOM',
  NULL,
  NULL,
  'Capacity: 50'
FROM facilities
WHERE code = 'DTHM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DTHM-OFR / OFFICE ROOM',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'DTHM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ISRDS TRAINING ROOM',
  NULL,
  NULL,
  'Capacity: 50'
FROM facilities
WHERE code = 'ISRDS'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'SKILLS LABORATORY',
  NULL,
  NULL,
  'Capacity: 60'
FROM facilities
WHERE code = 'DON'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'SMALL ROOM',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DON'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'STUDENT CENTER',
  NULL,
  NULL,
  'Capacity: 90'
FROM facilities
WHERE code = 'DON'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ADE-131',
  NULL,
  1,
  'Capacity: 40'
FROM facilities
WHERE code = 'DTE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ADE-132',
  NULL,
  1,
  'Capacity: 50'
FROM facilities
WHERE code = 'DTE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ADE-133',
  NULL,
  1,
  'Capacity: 40'
FROM facilities
WHERE code = 'DTE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ADE-213',
  NULL,
  2,
  'Capacity: 40'
FROM facilities
WHERE code = 'DTE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ADE-214',
  NULL,
  2,
  'Capacity: 50'
FROM facilities
WHERE code = 'DTE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ADE-236',
  NULL,
  2,
  'Capacity: 100'
FROM facilities
WHERE code = 'DTE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'ADE-237',
  NULL,
  2,
  'Capacity: 60'
FROM facilities
WHERE code = 'DTE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'DTE-AACCUP',
  NULL,
  NULL,
  'Capacity: 15'
FROM facilities
WHERE code = 'DTE'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'GYM',
  NULL,
  NULL,
  'Capacity: 600'
FROM facilities
WHERE code = 'IHK'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'IHK-101',
  NULL,
  1,
  'Capacity: 35'
FROM facilities
WHERE code = 'IHK'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'IHK-102',
  NULL,
  1,
  'Capacity: 35'
FROM facilities
WHERE code = 'IHK'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'IHK-103',
  NULL,
  1,
  'Capacity: 35'
FROM facilities
WHERE code = 'IHK'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'IHK-104',
  NULL,
  1,
  'Capacity: 35'
FROM facilities
WHERE code = 'IHK'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'IHK-Conf. Rm',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'IHK'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'IHK-Dance Rm',
  NULL,
  NULL,
  'Capacity: 30'
FROM facilities
WHERE code = 'IHK'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'VM-B1',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DVM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'VM-B12',
  NULL,
  NULL,
  'Capacity: 40'
FROM facilities
WHERE code = 'DVM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'VM-B14',
  NULL,
  NULL,
  'Capacity: 50'
FROM facilities
WHERE code = 'DVM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'VM-B2',
  NULL,
  NULL,
  'Capacity: 60'
FROM facilities
WHERE code = 'DVM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'VM-C1',
  NULL,
  NULL,
  'Capacity: 20'
FROM facilities
WHERE code = 'DVM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'VM-C11',
  NULL,
  NULL,
  'Capacity: 35'
FROM facilities
WHERE code = 'DVM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'VM-C12',
  NULL,
  NULL,
  'Capacity: 35'
FROM facilities
WHERE code = 'DVM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'VM-C13',
  NULL,
  NULL,
  'Capacity: 35'
FROM facilities
WHERE code = 'DVM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'VM-C14',
  NULL,
  NULL,
  'Capacity: 35'
FROM facilities
WHERE code = 'DVM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'VM-C4',
  NULL,
  NULL,
  'Capacity: 35'
FROM facilities
WHERE code = 'DVM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

INSERT INTO rooms (facility_id, room_code, name, floor, description)
SELECT id,
  'VM-C5',
  NULL,
  NULL,
  'Capacity: 35'
FROM facilities
WHERE code = 'DVM'
ON CONFLICT (facility_id, room_code) DO UPDATE SET
  name = EXCLUDED.name,
  floor = EXCLUDED.floor,
  description = EXCLUDED.description;

COMMIT;
